// Generated by scripts/sync-photo-library.mjs. Do not edit by hand.
export type PhotoAlbum = {
  slug: string;
  mapCity: string;
  local: string;
  country: string;
  countryLocal: string;
  hero: string;
  photos: string[];
  story: string;
};

export const photoAlbums: PhotoAlbum[] = [
  {
    "slug": "altay",
    "mapCity": "Altay",
    "local": "阿勒泰 · 新疆",
    "country": "China",
    "countryLocal": "中国",
    "hero": "photos/altay/cover.webp",
    "photos": [
      "photos/altay/01.webp",
      "photos/altay/02.webp",
      "photos/altay/03.webp",
      "photos/altay/04.webp",
      "photos/altay/05.webp"
    ],
    "story": "AI Story 正在构思中。未来这里将根据你的照片与旅程，生成只属于这座城市的摄影记忆。"
  },
  {
    "slug": "istanbul",
    "mapCity": "Istanbul",
    "local": "伊斯坦布尔",
    "country": "Türkiye",
    "countryLocal": "土耳其",
    "hero": "photos/istanbul/cover.webp",
    "photos": [
      "photos/istanbul/01.webp",
      "photos/istanbul/02.webp",
      "photos/istanbul/03.webp",
      "photos/istanbul/04.webp",
      "photos/istanbul/05.webp"
    ],
    "story": "AI Story 正在构思中。未来这里将根据你的照片与旅程，生成只属于这座城市的摄影记忆。"
  },
  {
    "slug": "osaka",
    "mapCity": "Osaka",
    "local": "大阪",
    "country": "Japan",
    "countryLocal": "日本",
    "hero": "photos/osaka/cover.webp",
    "photos": [
      "photos/osaka/01.webp",
      "photos/osaka/02.webp",
      "photos/osaka/03.webp",
      "photos/osaka/04.webp",
      "photos/osaka/05.webp"
    ],
    "story": "AI Story 正在构思中。未来这里将根据你的照片与旅程，生成只属于这座城市的摄影记忆。"
  },
  {
    "slug": "tawau",
    "mapCity": "Tawau",
    "local": "仙本那",
    "country": "Malaysia",
    "countryLocal": "马来西亚",
    "hero": "photos/tawau/cover.webp",
    "photos": [
      "photos/tawau/01.webp",
      "photos/tawau/02.webp",
      "photos/tawau/03.webp",
      "photos/tawau/04.webp",
      "photos/tawau/05.webp"
    ],
    "story": "AI Story 正在构思中。未来这里将根据你的照片与旅程，生成只属于这座城市的摄影记忆。"
  },
  {
    "slug": "tokyo",
    "mapCity": "Tokyo",
    "local": "东京",
    "country": "Japan",
    "countryLocal": "日本",
    "hero": "photos/tokyo/cover.webp",
    "photos": [
      "photos/tokyo/01.webp",
      "photos/tokyo/02.webp",
      "photos/tokyo/03.webp",
      "photos/tokyo/04.webp",
      "photos/tokyo/05.webp"
    ],
    "story": "AI Story 正在构思中。未来这里将根据你的照片与旅程，生成只属于这座城市的摄影记忆。"
  }
];

export const photoAlbumsBySlug = new Map(photoAlbums.map((album) => [album.slug, album]));
export const photoAlbumsByCity = new Map(photoAlbums.map((album) => [album.mapCity, album]));
